extends: eslint:recommended
env:
  node: true
  commonjs: true
  es6: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
rules:
  no-console: off
  prefer-const: error
  eqeqeq:
    - error
    - smart
