extends: eslint:recommended
env:
  node: true
  commonjs: true
  es6: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
plugins:
  - fp
rules:
  no-console: off
  prefer-const: error
  no-else-return: error
  require-await: error
  fp/no-loops: error
  fp/no-let: error
  fp/no-mutation: 
    - error
    - commonjs: true
      allowThis: true
  fp/no-mutating-methods: error
  eqeqeq:
    - error
    - smart
